name: Continuous Integration (CI)

on:
    push:
        branches: 
            - "main"
        tags:
            - 'v*' # Triggers on tags starting with 'v', e.g., v1.0.0, v2.1
            - 'release-*' # Triggers on tags starting with 'release-', e.g., release-20250726
            - '**' # Triggers on any tag push
    pull_request:
        branches:
            - "main"
    workflow_dispatch:

jobs:
    build:
        name: Build and Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                persist-credentials: false

            - name: Set up Python 3.10
              uses: actions/setup-python@v5
              with:
                python-version: "3.10"
            
            - name: Install build tools
              run: >-
                python3 -m pip install build --user

            - name: Run a multi-line script
              run: |
                echo Add other actions to build,
                echo test, and deploy your project.
                echo "The GitHub Run ID is: ${{ github.run_id }}"

            - name: Build a binary wheel and a source tarball
              env:
                # Environment variables can be set here
                RELEASE_VERSION: "${{ github.run_id }}-xxx"
              run: python3 -m build

            - name: Store the distribution packages
              uses: actions/upload-artifact@v4
              with:
                name: python-package-distributions
                path: dist/

            - name: Run a one-line script
              run: ls
            


    publish-to-pypi:
        name: Publish to PyPI
        runs-on: ubuntu-latest
        needs:
            - build
        steps:
            - name: Run a one-line script
              run: echo "This job is a placeholder for publishing to PyPI."

    publish-to-testpypi:
        name: Publish to PyPI
        runs-on: ubuntu-latest
        needs:
            - build
        steps:
            - name: Run a one-line script
              run: echo "This job is a placeholder for publishing to PyPI."