name: Continuous Integration (CI)

on:
    push:
        branches: 
            - "main"
        tags:
            - 'v*' # Triggers on tags starting with 'v', e.g., v1.0.0, v2.1
            - 'release-*' # Triggers on tags starting with 'release-', e.g., release-20250726
            - '**' # Triggers on any tag push
    pull_request:
        branches:
            - "main"
    workflow_dispatch:
        inputs:
            version_override:
                description: 'Version override'
                required: false
                type: string

jobs:
    build:
        name: Build and Test
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: pwsh
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                persist-credentials: false

            - name: Set up Python 3.10
              uses: actions/setup-python@v5
              with:
                python-version: "3.10"
            
            - name: Install build tools
              run: >-
                python3 -m pip install build --user

            - name: Versioning
              run: |
                Write-Host "Version override    : ${{ github.event.inputs.version_override }}"
                Write-Host "GitHub run id       : ${{ github.run_id }}"
                Write-Host "GitHub run attempt  : ${{ github.run_attempt }}"
                Write-Host "GitHub run number   : ${{ github.run_number }}"
                $versionConfig = (Get-Content .\version-config.json | ConvertFrom-Json)
                Write-Host "Version (Major)     : $versionConfig.major"
                Write-Host "Version (Minor)     : $versionConfig.minor"
                Write-Host "Version (Patch)     : $versionConfig.patch"
                $latestVersionNumber = "$($versionConfig.major).$($versionConfig.minor).$($versionConfig.patch + ${{ github.run_number }})"
                Write-Host "latestVersionNumber : $latestVersionNumber"
                Add-Content -Path $env:GITHUB_ENV -Value "APP_VERSION=$latestVersionNumber"
                Write-Host "APP_VERSION environment variable set."
                Add-Content -Path $env:GITHUB_ENV -Value "RELEASE_VERSION=$latestVersionNumber"

            - name: Use the extracted version in a different step (PowerShell)
              run: |
                Write-Host "Building application version: $($env:APP_VERSION)"
                Write-Host "Simulating a build process for version $($env:APP_VERSION)..."
                Get-ChildItem # Just to show another command running (PowerShell equivalent of ls -la)


            - name: Build a binary wheel and a source tarball
              # env:
              #   RELEASE_VERSION: "${{ github.run_number }}"
              run: python3 -m build

            - name: Store the distribution packages
              uses: actions/upload-artifact@v4
              with:
                name: python-package-distributions
                path: dist/

            - name: Run a one-line script
              run: ls -R
            


    publish-to-pypi:
        name: Publish to PyPI
        runs-on: ubuntu-latest
        needs:
            - build
        steps:
            - name: Run a one-line script
              run: echo "This job is a placeholder for publishing to PyPI."

    publish-to-testpypi:
        name: Publish to TestPyPI
        runs-on: ubuntu-latest
        needs:
            - build
        steps:
            - name: Run a one-line script
              run: echo "This job is a placeholder for publishing to PyPI."