name: Development Workflow

run-name: Development workflow -- ${{ github.run_id }}

on:
    push:
        branches: 
            - "main"

jobs:
    publish:
        name: Publish Python Package to PyPI
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: pwsh
        environment:
            name: pypi
        steps:
            - name: List downloaded files (for debugging)
              run: Write-Host "Listing files in the current directory:"; ls -R

    update_wiki:
        name: Update wiki
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: pwsh
        permissions:
            contents: write # Grant write permission

        steps:
          - name: Checkout main repository
            uses: actions/checkout@v4

          - name: Clone wiki repository
            run: |
              git clone https://github.com/${{ github.repository }}.wiki.git wiki-repo
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Or your PAT if cross-repo

          - name: Copy wiki files
            run: |
              #rsync -av --delete wiki/ wiki-repo/ # Syncs content from your 'wiki/' folder to the cloned wiki repo
              # Alternatively, you can generate content in this step and output to wiki-repo/
              # For example: echo "# My New Wiki Page" > wiki-repo/New-Page.md
              Write-Host "# My New Wiki Page" > wiki-repo/New-Page.md

          - name: Commit and push to wiki
            working-directory: ./wiki-repo # Perform Git operations in the cloned wiki repo
            run: |
              git config user.name "github-actions[bot]"
              git config user.email "github-actions[bot]@users.noreply.github.com"
              git add .
              git commit -m "Update wiki from GitHub Actions [skip ci]" || echo "No changes to commit"
              # git push
              # Use the GITHUB_TOKEN directly in the push URL for authentication
              git push https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git
